// describe('BankApplication',async() => { 
//      it('homepage',async()=>{
//         await browser.url('https://www.bankofamerica.com/')
//         browser.getTitle()
//         browser.maximizeWindow()
//         await browser.$('//a[text()="Open an Account"]').click()
//         await browser.$('(//a[@class="cta cta"])[2]').click()
//         await browser.scroll(0,600)
//         const elem = await browser.$('//a[@id="learn_more_title_4071239~WM~en_US"]')
//         await elem.scrollIntoView()
//         const parentwindow = await browser.getWindowHandle();
//         await browser.$('//a[@id="terms_and_conditions_4071239~WM~en_US"]').click()
//         await browser.pause(3000)
//         // let parentframe = await browser.url('https://www.bankofamerica.com/credit-cards/?cm_sp=Cons-CC-_-HP_OAA2-_-CC16LT005N_HP_OAA2_Card-Link-on-HP_OAA2-Landing-Page')
//         // await browser.switchToFrame(parentframe)
//         await browser.switchToWindow(parentwindow)
//         // await browser.switchToParentFrame()
//         await browser.$('//a[@id="home_4071239~WM~en_US"]').doubleClick()
//         await browser.$('//a[@id="signInSaveTime"]').Click()
        
//         // await browser.$('(//input[@type="text"])[1]').setValue("Avi")
//         // await browser.$('(//input[@type="text"])[2]').setValue("ku")
//         // await browser.$('(//input[@type="text"])[3]').setValue("chauhan")
//         // await browser.$('(//input[@type="text"])[4]').setValue("abc street no5")
//         // await browser.$('(//input[@type="text"])[5]').setValue("cdef street 20")
//         // await browser.$('(//input[@type="text"])[6]').setValue("bangalore")
//         // await browser.$('(//input[@type="text"])[6]').setValue("bangalore")
//         // await browser.$('//select[@id="customerAddressState"]').selectByVisibleText("Indiana")
//         // await browser.$('(//input[@type="text"])[7]').setValue("45628")
//         // await browser.$('(//input[@type="checkbox"])[1]').click()
//         // await browser.$('(//input[@data-field-type="phone"])[1]').setValue("456123789")
//         // await browser.$('//input[@id="phoneNumberMobile"]').click()
//         await browser.pause(5000)
//     })
//  })