// describe('Orange Hrm', async() => { 
//     it('testscript',async()=>{
//         await browser.url('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
//         await browser.maximizeWindow()
//         await browser.$('//input[@placeholder="Username"]').setValue("Admin")
//         // await browser.scroll(0,600)
//         await browser.$('//input[@placeholder="Password"]').setValue("admin123")
//         await browser.$('//button[@type="submit"]').click()
//         await browser.$('//a[contains(@href,"/web/index.php/time/viewTimeModule")]').click()
//         await browser.$('(//span[@class="oxd-topbar-body-nav-tab-item"])[4]').click() 
//         await browser.$('(//a[@role="menuitem"])[2]').click() 
//         await browser.$('(//input[contains(@placeholder,"Type for hints...")])[1]').setValue("ACME Ltd") 
//         await browser.$('//button[@type="submit"]').click() 
//         await browser.$('(//button[@type="button"])[6]').click() 
    
//         // await browser.$('(//div[text()="-- Select --"])[1]').selectByVisibleText(2)
//         // await browser.acceptAlert()
//         // await browser.scroll(0,600)
//         await browser.pause(4000)
//     })
//  })